// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbE3Q_ksX8rFn-_pzU_ZWEpiDVFI_RiDI',
    appId: '1:37092018117:web:8b7aa5fea8710152e16dac',
    messagingSenderId: '37092018117',
    projectId: 'equitycircle-86363',
    authDomain: 'equitycircle-86363.firebaseapp.com',
    storageBucket: 'equitycircle-86363.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJNCHij12lr2-uNiEqTW746MCk6RdRqUs',
    appId: '1:37092018117:android:dcd0859cdad2c0a5e16dac',
    messagingSenderId: '37092018117',
    projectId: 'equitycircle-86363',
    storageBucket: 'equitycircle-86363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwVl6ez8SyQVOx_eKw3e-U14di_L1OhFE',
    appId: '1:37092018117:ios:88d00823a447ec0fe16dac',
    messagingSenderId: '37092018117',
    projectId: 'equitycircle-86363',
    storageBucket: 'equitycircle-86363.firebasestorage.app',
    androidClientId: '37092018117-1osl7b8v128dije5kdohlhcs1shcm5b3.apps.googleusercontent.com',
    iosClientId: '37092018117-fj0cnnlicd5pco0b79c0o052aklkt3t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.equitycircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwVl6ez8SyQVOx_eKw3e-U14di_L1OhFE',
    appId: '1:37092018117:ios:88d00823a447ec0fe16dac',
    messagingSenderId: '37092018117',
    projectId: 'equitycircle-86363',
    storageBucket: 'equitycircle-86363.firebasestorage.app',
    androidClientId: '37092018117-1osl7b8v128dije5kdohlhcs1shcm5b3.apps.googleusercontent.com',
    iosClientId: '37092018117-fj0cnnlicd5pco0b79c0o052aklkt3t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.equitycircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbE3Q_ksX8rFn-_pzU_ZWEpiDVFI_RiDI',
    appId: '1:37092018117:web:e068f4f50e99c205e16dac',
    messagingSenderId: '37092018117',
    projectId: 'equitycircle-86363',
    authDomain: 'equitycircle-86363.firebaseapp.com',
    storageBucket: 'equitycircle-86363.firebasestorage.app',
  );
}
